Libraries and options

In [1]:
import numpy as np, pandas as pd, sys, os, re, zipfile, shutil, pickle, matplotlib.pyplot as plt, seaborn as sns, bz2,time
import json
pd.options.display.max_columns = 500
pd.options.display.max_rows = 500
pd.options.display.max_colwidth = 50

In [2]:
def get_counties_df(file_name='../covid/config/counties.json'):
    with open(file_name) as file:
                county_data = json.load(file)
    
    df = pd.DataFrame.from_dict(county_data)
    
    data = [df[col] for col in df.columns]    
    
    # pivot
    return pd.DataFrame(data,columns=df.index, index=df.columns)
    
counties = get_counties_df()

In [3]:
# counties['fips'] = counties['fips']['id'].astype(str)

a = [x['id'] for x in counties['fips'][~counties['fips'].isnull()] ]
counties.loc[counties['fips'].notnull(),'fips'] = a

In [4]:
counties

,hospitalIcuBeds,hospitalStaffedBeds,hospitalLicensedBeds,latestTotalPopulation,location,fips,id,name,version,typeIdent
Autauga_Alabama_UnitedStates,6.0,55.0,85.0,55869.0,{'value': {'id': 'Autauga_Alabama_UnitedStates...,01001,Autauga_Alabama_UnitedStates,Autauga,3735560.0,EP_LOC
Baldwin_Alabama_UnitedStates,51.0,362.0,386.0,223234.0,{'value': {'id': 'Baldwin_Alabama_UnitedStates...,01003,Baldwin_Alabama_UnitedStates,Baldwin,3801096.0,EP_LOC
Barbour_Alabama_UnitedStates,5.0,30.0,74.0,24686.0,{'value': {'id': 'Barbour_Alabama_UnitedStates...,01005,Barbour_Alabama_UnitedStates,Barbour,3801096.0,EP_LOC
Bibb_Alabama_UnitedStates,4.0,25.0,35.0,22394.0,"{'value': {'id': 'Bibb_Alabama_UnitedStates'},...",01007,Bibb_Alabama_UnitedStates,Bibb,3997704.0,EP_LOC
Blount_Alabama_UnitedStates,6.0,25.0,25.0,57826.0,{'value': {'id': 'Blount_Alabama_UnitedStates'...,01009,Blount_Alabama_UnitedStates,Blount,3801096.0,EP_LOC
...,...,...,...,...,...,...,...,...,...,...
Unassigned_Wisconsin_UnitedStates,NaN,NaN,NaN,NaN,{'value': {'id': 'Unassigned_Wisconsin_UnitedS...,NaN,Unassigned_Wisconsin_UnitedStates,Unassigned,3080195.0,EP_LOC
Unassigned_Wyoming_UnitedStates,NaN,NaN,NaN,NaN,{'value': {'id': 'Unassigned_Wyoming_UnitedSta...,NaN,Unassigned_Wyoming_UnitedStates,Unassigned,3080201.0,EP_LOC
Unassigned_Guam_UnitedStates,NaN,NaN,NaN,NaN,NaN,NaN,Unassigned_Guam_UnitedStates,Unknown,1.0,EP_LOC
Unassigned_NorthernMarianaIslands_UnitedStates,NaN,NaN,NaN,NaN,{'value': {'id': 'Unassigned_NorthernMarianaIs...,NaN,Unassigned_NorthernMarianaIslands_UnitedStates,Unknown,458755.0,EP_LOC
Unassigned_PuertoRico_UnitedStates,NaN,NaN,NaN,NaN,NaN,NaN,Unassigned_PuertoRico_UnitedStates,Unknown,1.0,EP_LOC

Importing census data

In [86]:
censusDF = pd.read_csv('./censusData.csv')
varDF = pd.read_csv("./acs2019Variables.csv", skiprows=[1,2,3])
pd.options.display.max_colwidth=1000
#change state and county fip codes to strings with standard lengths
censusDF['state'] = censusDF['state'].astype(str).str.zfill(2)
censusDF['county'] = censusDF['county'].astype(str).str.zfill(3)
#join these to create the combined fips code
censusDF['fips'] = censusDF['state']+censusDF['county']
#create a list of descriptive variable names in the same order as in censusDF
a = []
for i in censusDF.columns[:-4]:
    vName = varDF['label'][varDF['name']==i].to_string(index=False)+varDF['concept'][varDF['name']==i].to_string(index=False)
    a.append(vName)
for i in censusDF.columns[-4:]:
    a.append(i)
#rebuild dataframe with these column names
# censusDF = pd.DataFrame(censusDF.values, columns=a)
#et voila

In [163]:
a = counties.index
x = [re.search('.*(?=_UnitedStates)',x).group(0).split('_') for x in a]
x,y = zip(*x)
counties['coName'] = x
counties['stName'] = y

In [239]:
def getCounty( c ):
    toby =  []
    for x in c:
        try:
            toby.append(re.search('.*(?=\sCounty)',x).group(0))
        except:
            toby.append(re.search('.*(?=, )',x).group(0))
    return toby

def getState( c ):
    toby =  []
    for x in c:
        try:
            toby.append(re.search('(?<=, ).*',x).group(0))
        except:
            print('problem')
    return toby

t = nCoDF.iloc[0:1].values
t=t[0]
t[1]
counties['state'].unique()
a =  censusDF.NAME.values
x = getCounty(a)
censusDF['coName'] =  x
y = getState(a)
y
censusDF['stName'] = y
censusDF[['coName','stName','fips']]

# [counties[x].index for x in counties.index if re.match('Unassigned_',x)]
biggy = []
for x in counties.index:
    if re.match('Unassigned_|Outof',x):
        biggy.append(x)
counties.drop(biggy,inplace=True)
counties.tail()

,hospitalIcuBeds,hospitalStaffedBeds,hospitalLicensedBeds,latestTotalPopulation,location,fips,id,name,version,typeIdent,county,state
Uinta_Wyoming_UnitedStates,6.0,105.0,225.0,20226.0,"{'value': {'id': 'Uinta_Wyoming_UnitedStates'}, 'timestamp': '2020-05-09T00:00:00Z'}",56041,Uinta_Wyoming_UnitedStates,Uinta,3932178.0,EP_LOC,Uinta,Wyoming
Washakie_Wyoming_UnitedStates,3.0,18.0,18.0,7805.0,"{'value': {'id': 'Washakie_Wyoming_UnitedStates'}, 'timestamp': '2020-05-09T00:00:00Z'}",56043,Washakie_Wyoming_UnitedStates,Washakie,3932179.0,EP_LOC,Washakie,Wyoming
Weston_Wyoming_UnitedStates,NaN,NaN,NaN,6927.0,"{'value': {'id': 'Weston_Wyoming_UnitedStates'}, 'timestamp': '2020-04-05T20:12:58Z'}",NaN,Weston_Wyoming_UnitedStates,Weston_Wyoming_UnitedStates,1376265.0,EP_LOC,Weston,Wyoming
DukesandNantucket_Massachusetts_UnitedStates,NaN,NaN,NaN,NaN,"{'value': {'id': 'DukesandNantucket_Massachusetts_UnitedStates'}, 'timestamp': '2020-05-09T00:00:00Z'}",NaN,DukesandNantucket_Massachusetts_UnitedStates,Dukes and Nantucket,3276801.0,EP_LOC,DukesandNantucket,Massachusetts
KansasCity_Missouri_UnitedStates,NaN,NaN,NaN,NaN,"{'value': {'id': 'KansasCity_Missouri_UnitedStates'}, 'timestamp': '2020-05-09T00:00:00Z'}",NaN,KansasCity_Missouri_UnitedStates,Kansas City,3342337.0,EP_LOC,KansasCity,Missouri

In [299]:
bu = counties[['county','fips']][counties['state']=='Wyoming'].sort_values('county')
al = censusDF[['coName','fips']][censusDF['stName']=='Wyoming'].sort_values('coName')
bu.rename(columns={'county': 'coName'},inplace=True)
# bu['county'] = [x for x in bu['county'].values]
bu['coName'] = [re.sub('(?<=[a-z])(?=[A-Z])',' ',x) for x in bu['coName'].values]

In [301]:
counties.tail()

,hospitalIcuBeds,hospitalStaffedBeds,hospitalLicensedBeds,latestTotalPopulation,location,fips,id,name,version,typeIdent,county,state
Uinta_Wyoming_UnitedStates,6.0,105.0,225.0,20226.0,"{'value': {'id': 'Uinta_Wyoming_UnitedStates'}, 'timestamp': '2020-05-09T00:00:00Z'}",56041,Uinta_Wyoming_UnitedStates,Uinta,3932178.0,EP_LOC,Uinta,Wyoming
Washakie_Wyoming_UnitedStates,3.0,18.0,18.0,7805.0,"{'value': {'id': 'Washakie_Wyoming_UnitedStates'}, 'timestamp': '2020-05-09T00:00:00Z'}",56043,Washakie_Wyoming_UnitedStates,Washakie,3932179.0,EP_LOC,Washakie,Wyoming
Weston_Wyoming_UnitedStates,NaN,NaN,NaN,6927.0,"{'value': {'id': 'Weston_Wyoming_UnitedStates'}, 'timestamp': '2020-04-05T20:12:58Z'}",NaN,Weston_Wyoming_UnitedStates,Weston_Wyoming_UnitedStates,1376265.0,EP_LOC,Weston,Wyoming
DukesandNantucket_Massachusetts_UnitedStates,NaN,NaN,NaN,NaN,"{'value': {'id': 'DukesandNantucket_Massachusetts_UnitedStates'}, 'timestamp': '2020-05-09T00:00:00Z'}",NaN,DukesandNantucket_Massachusetts_UnitedStates,Dukes and Nantucket,3276801.0,EP_LOC,DukesandNantucket,Massachusetts
KansasCity_Missouri_UnitedStates,NaN,NaN,NaN,NaN,"{'value': {'id': 'KansasCity_Missouri_UnitedStates'}, 'timestamp': '2020-05-09T00:00:00Z'}",NaN,KansasCity_Missouri_UnitedStates,Kansas City,3342337.0,EP_LOC,KansasCity,Missouri

Importing covid data

In [8]:
path = r'../covid/processed_data/county_merged_parts/'
listFiles = []
for r, d, files in os.walk(path):
    for file in files:
        listFiles.append(file)

testDF = pd.DataFrame()
for i,file in enumerate(listFiles):
    inDF = pd.read_pickle(f'{path}{file}')
    inDF['bigName'] = inDF.index
    inDF.reset_index(level=0,inplace=True)
    testDF = pd.concat([testDF,inDF],ignore_index=True)

In [ ]:
print(testDF.shape)
mask = testDF.isnull().any(axis=0)
noNullDF = testDF.loc[:,~mask]
print(noNullDF.shape)
testDF[testDF['fips'].isnull()]

In [11]:
testDF['bigName']

0          2020-01-01
1          2020-01-02
2          2020-01-03
3          2020-01-04
4          2020-01-05
              ...
2122225    2021-10-11
2122226    2021-10-12
2122227    2021-10-13
2122228    2021-10-14
2122229    2021-10-15
Name: bigName, Length: 2122230, dtype: object

In [ ]:
path = r'../covid/processed_data/county_merged_parts/'
listFiles = []
for r, d, files in os.walk(path):
    for file in files:
        listFiles.append(file)

testDF = pd.DataFrame()
for i,file in enumerate(listFiles):
    inDF = pd.read_pickle(f'{path}{file}')
    inDF.reset_index(level=0,inplace=True)
    testDF = pd.concat([testDF,inDF],ignore_index=True)
# test = f'{path}{listFiles[0]}'
# testDF= pd.read_pickle(test)

# mask = testDF['fips'].isnull()
testDF.dropna(subset=['fips'], inplace=True)

testDF['fips']=testDF['fips'].astype(int).astype(str)

testDF['fips'] = testDF['fips'].str.zfill(5)

Joining census and covid data

In [ ]:
newDF = testDF.join(censusDF.set_index('fips'),on='fips',how='left')

Exported this DF for future work

In [ ]:
# newDF.to_csv('covidCensus.gz',index=False,compression='gzip')

Imported back

In [2]:
anotherDF = pd.read_csv('covidCensus.gz')
anotherDF['fips'] = anotherDF['fips'].astype(str)
anotherDF['dates']=pd.to_datetime(anotherDF['dates'])

Import air quality data

In [3]:
path = r'../air_quality/'
dirs = next(os.walk(path))[1]
airDF = pd.DataFrame()
cols = []
for dir in dirs:
    files = next(os.walk(f'{path}{dir}/unzipped/'))[2]
    for m,file in enumerate(files):
        inDF = pd.read_csv(f'{path}{dir}/unzipped/{file}')
        cols.append(inDF.columns.values)
        inDF['Date of Last Change'] = pd.to_datetime(inDF['Date of Last Change'])
        inDF['fips'] = inDF['fips'].astype(str).str.zfill(5)
        prefix = re.search('(?<=daily_)[^_]*(?=_)', f'{file}').group(0)
        print(prefix)
        inDF['pollutant'] = prefix
#         inDF = inDF.add_prefix(prefix+'_')
        airDF =pd.concat([airDF,inDF],ignore_index=True)

lead
lead
lead
no2
no2
no2
ozone
ozone
ozone

C:\Users\richs\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (27) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

pm25
pm25
pm25

In [7]:
airDF.columns

Index(['State Code', 'County Code', 'Site Num', 'Parameter Code', 'POC',
       'Latitude', 'Longitude', 'Datum', 'Parameter Name', 'Sample Duration',
       'Pollutant Standard', 'Date Local', 'Units of Measure', 'Event Type',
       'Observation Count', 'Observation Percent', 'Arithmetic Mean',
       '1st Max Value', '1st Max Hour', 'AQI', 'Method Code', 'Method Name',
       'Local Site Name', 'Address', 'State Name', 'County Name', 'City Name',
       'CBSA Name', 'Date of Last Change', 'fips', 'pollutant', 'Mean ugm3'],
      dtype='object')

In [ ]:
for m,col in enumerate(cols[1:]):
    try:
        print(m+1,all(col==cols[0]),"col0")
    except:
        print(m+1,all(col==cols[3]),"col3")

In [ ]:
# pm25DF['Date of Last Change']
anotherDF['dates']

In [8]:
print(anotherDF['dates'].dtype)
print(airDF['Date of Last Change'].dtype)
print(anotherDF['fips'].dtype)
print(airDF['fips'].dtype)

datetime64[ns]
datetime64[ns]
object
object

Put it all together

In [4]:
newDF = anotherDF.merge(airDF, left_on=['dates','fips'], right_on=['Date of Last Change','fips'], how='outer')

In [3]:
# newDF.to_csv('allTogetherNow.gz',index=False,compression='gzip')
# outfile = open('allTogetherNow.pkl','wb')
# pickle.dump(newDF,outfile)
# outfile.close()

# newDF.to_csv('allTogetherNow.bz2',index=False,compression='bz2')

# newDF.to_csv('allTogetherNow.gz',index=False,compression='gzip')
with bz2.BZ2File('allTogetherNow.pbz2','wb') as f:
    pickle.dump(newDF,f)

Import back in

In [5]:
def importBz2( file ):
    start = time.time()
    data = bz2.BZ2File(file,'rb')
    # newDF = pd.read_pickle('allTogetherNow.pkl')
    return pd.read_csv(data), print(time.time()-start)

newDF = importBz2('allTogetherNow.bz2')

C:\Users\richs\AppData\Local\Temp/ipykernel_7844/3713116299.py:7: DtypeWarning: Columns (0,85,95,96,97,98,99,100,101,109,110,111,112,113,114,115,116,117) have mixed types.Specify dtype option on import or set low_memory=False.
  newDF = importBz2('allTogetherNow.bz2')

167.45737767219543

In [3]:
def importPbz2( file ):
    start = time.time()
    data = bz2.BZ2File(file,'rb')
    # newDF = pd.read_pickle('allTogetherNow.pkl')
    return pd.read_pickle(data), print(time.time()-start)

newDF = importPbz2('allTogetherNow.pbz2')

51.35800099372864

And explore...

In [ ]:
print(newDF.shape)
mask = newDF.isnull().any(axis=0)
noNullDF = newDF.loc[:,~mask]
print(noNullDF.shape)

In [21]:
newDF['density']=newDF['latestTotalPopulation']/newDF['LND110210']

In [22]:
# a = [x for x in newDF if x.startswith('ozone')]
b = [x for x in newDF if (x.startswith('JHU')|x.startswith('NYT'))&(~x.endswith('missing'))&('Confirmed' in x)]
# b.extend(a)
b
no2DF = newDF.loc[newDF['pollutant']=='no2',b+['Observation Count','Observation Percent','Arithmetic Mean',\
                                                           '1st Max Value','Mean ugm3','fips','dates','density']]
# ozoneDF.dropna(subset=a,inplace=True)

In [29]:
# ozoneDF.dropna(subset=['Mean ugm3'],inplace=True)
no2fipsDF = no2DF[(no2DF['dates']>='2020-03-11')&(no2DF['dates']<='2021-03-11')].groupby(by=['fips']).agg({'JHU_ConfirmedDeaths.data': 'max', 'NYT_ConfirmedDeaths.data': 'max',\
                              'Mean ugm3': 'mean','density': 'max'})

In [30]:
no2fipsDF.corr()

,JHU_ConfirmedDeaths.data,NYT_ConfirmedDeaths.data,Mean ugm3,density
JHU_ConfirmedDeaths.data,1.000000,0.999807,0.469625,0.449120
NYT_ConfirmedDeaths.data,0.999807,1.000000,0.469777,0.448001
Mean ugm3,0.469625,0.469777,1.000000,0.580541
density,0.449120,0.448001,0.580541,1.000000

In [26]:
def covidPollutantFipsCorr(df, pollutant, cols=[]):
    if cols:
        polDF =  df.loc[df['pollutant']==pollutant,cols+['fips']]
    else:
        polDF = df.loc[df['pollutant']==pollutant,:]
    fipsDF  = polDF.groupby(by='fips').agg('mean')
    return fipsDF.corr()

In [31]:
dateFilterDF = newDF[(newDF['dates']>='2020-03-11')|(newDF['dates']<='2021-03-11')]

NO2

In [42]:
covidPollutantFipsCorr(dateFilterDF, 'no2', b[:5]+['Arithmetic Mean','density'])

,JHU_ConfirmedCases.data,NYT_ConfirmedCases.data,JHU_ConfirmedDeaths.data,JHU_ConfirmedRecoveries.data,NYT_ConfirmedDeaths.data,Arithmetic Mean,density
JHU_ConfirmedCases.data,1.000000,0.999370,0.934337,NaN,0.933333,0.435601,0.347623
NYT_ConfirmedCases.data,0.999370,1.000000,0.933436,NaN,0.932854,0.438036,0.346395
JHU_ConfirmedDeaths.data,0.934337,0.933436,1.000000,NaN,0.999769,0.472795,0.434318
JHU_ConfirmedRecoveries.data,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NYT_ConfirmedDeaths.data,0.933333,0.932854,0.999769,NaN,1.000000,0.471129,0.432409
Arithmetic Mean,0.435601,0.438036,0.472795,NaN,0.471129,1.000000,0.532606
density,0.347623,0.346395,0.434318,NaN,0.432409,0.532606,1.000000

Lead

In [43]:
covidPollutantFipsCorr(dateFilterDF, 'lead', b[:5]+['Arithmetic Mean','density'])

,JHU_ConfirmedCases.data,NYT_ConfirmedCases.data,JHU_ConfirmedDeaths.data,JHU_ConfirmedRecoveries.data,NYT_ConfirmedDeaths.data,Arithmetic Mean,density
JHU_ConfirmedCases.data,1.000000,0.999995,0.986252,NaN,0.987367,-0.078670,0.415553
NYT_ConfirmedCases.data,0.999995,1.000000,0.986216,NaN,0.987334,-0.078643,0.415348
JHU_ConfirmedDeaths.data,0.986252,0.986216,1.000000,NaN,0.999815,-0.076989,0.465977
JHU_ConfirmedRecoveries.data,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NYT_ConfirmedDeaths.data,0.987367,0.987334,0.999815,NaN,1.000000,-0.074662,0.459923
Arithmetic Mean,-0.078670,-0.078643,-0.076989,NaN,-0.074662,1.000000,-0.227619
density,0.415553,0.415348,0.465977,NaN,0.459923,-0.227619,1.000000

Ozone

In [44]:
covidPollutantFipsCorr(dateFilterDF, 'ozone', b[:5]+['Arithmetic Mean','density'])

,JHU_ConfirmedCases.data,NYT_ConfirmedCases.data,JHU_ConfirmedDeaths.data,JHU_ConfirmedRecoveries.data,NYT_ConfirmedDeaths.data,Arithmetic Mean,density
JHU_ConfirmedCases.data,1.000000,0.999442,0.936091,NaN,0.935396,-0.115189,0.456450
NYT_ConfirmedCases.data,0.999442,1.000000,0.935365,NaN,0.935056,-0.112181,0.456486
JHU_ConfirmedDeaths.data,0.936091,0.935365,1.000000,NaN,0.999585,-0.123963,0.495844
JHU_ConfirmedRecoveries.data,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NYT_ConfirmedDeaths.data,0.935396,0.935056,0.999585,NaN,1.000000,-0.121489,0.494708
Arithmetic Mean,-0.115189,-0.112181,-0.123963,NaN,-0.121489,1.000000,-0.168680
density,0.456450,0.456486,0.495844,NaN,0.494708,-0.168680,1.000000

PM2.5

In [45]:
covidPollutantFipsCorr(dateFilterDF, 'pm25', b[:5]+['Arithmetic Mean','density'])

,JHU_ConfirmedCases.data,NYT_ConfirmedCases.data,JHU_ConfirmedDeaths.data,JHU_ConfirmedRecoveries.data,NYT_ConfirmedDeaths.data,Arithmetic Mean,density
JHU_ConfirmedCases.data,1.000000,0.998959,0.918150,NaN,0.915564,-0.086795,0.411385
NYT_ConfirmedCases.data,0.998959,1.000000,0.916921,NaN,0.915038,-0.086633,0.410773
JHU_ConfirmedDeaths.data,0.918150,0.916921,1.000000,NaN,0.999400,-0.085107,0.510096
JHU_ConfirmedRecoveries.data,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NYT_ConfirmedDeaths.data,0.915564,0.915038,0.999400,NaN,1.000000,-0.086228,0.507456
Arithmetic Mean,-0.086795,-0.086633,-0.085107,NaN,-0.086228,1.000000,0.020543
density,0.411385,0.410773,0.510096,NaN,0.507456,0.020543,1.000000

In [80]:
a = no2fipsDF['Arithmetic Mean'].quantile([0,0.25,0.5,0.75,1])
b = no2fipsDF['JHU_ConfirmedDeaths.data'].quantile([0,0.25,0.5,0.75,1])

In [82]:
print(a)
print(b)

0.00     0.614572
0.25     2.990254
0.50     5.266662
0.75     8.579565
1.00    19.021019
Name: Arithmetic Mean, dtype: float64
0.00        0.0
0.25       91.0
0.50      343.0
0.75     1001.0
1.00    10020.0
Name: JHU_ConfirmedDeaths.data, dtype: float64

In [ ]:
corrs =  newDF.corr()

In [4]:
numbDF = newDF.loc[:,newDF.dtypes!='object']
corrs = numbDF.corr()

In [46]:
# # newDF.to_csv('allTogetherNow.gz',index=False,compression='gzip')
# with bz2.BZ2File('allTogetherNow.pbz2','wb') as f:
#     pickle.dump(newDF,f)